server:
  port: 8084
  servlet:
    context-path: /api

spring:
  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

mat-api-key: ${MAT_API_KEY:DISABLED}

info:
  app:
    name: Cql Elm Translation Services

madie:
  fhir:
    service:
      baseUrl: ${FHIR_SERVICES_URL:http://localhost:8085/api}
      libraries:
        uri: /hapiFhir/libraries

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    root: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
