- name: maven-settings-xml-action
  uses: whelk-io/maven-settings-xml-action@v20
  with:
    repositories: >
      [
        {
          "id": "central",
          "name": "Maven-central",
          "url": "https://repo1.maven.org/maven2",
          "releases": {
            "enabled": "true",
            "updatePolicy": "always",
            "checksumPolicy": "fail"
          },
          "snapshots": {
            "enabled": "false",
            "updatePolicy": "always",
            "checksumPolicy": "fail"
          }
        }
      ]
    plugin_repositories: >
      [
        {
          "id": "github",
          "name": "github-madie-rest-commons",
          "url": "https://maven.pkg.github.com/MeasureAuthoringTool/madie-rest-commons",
          "releases": {
            "enabled": "true"
          },
          "snapshots": {
            "enabled": "false"
          }
        },
        {
          "id": "github",
          "name": "github-madie-server-commons",
          "url": "https://maven.pkg.github.com/MeasureAuthoringTool/madie-server-commons",
          "releases": {
            "enabled": "true"
          },
          "snapshots": {
            "enabled": "false"
          }
        }
      ]
    servers: >
      [
        {
          "id": "github",
          "username": "${github.actor}",
          "password": "${secrets.GITHUB_TOKEN}",
          "configuration": {
            "httpConfiguration": {
              "all": {
                "usePreemptive": "true"
              }
            }
          }
        }
      ]
    active_profiles: >
      [
        "github"
      ]
    output_file: .m2/settings.xml